version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      target: backend
    ports:
      - 8000:8000
    # volumes:
    #   - .:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: "*"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      models:
        condition: service_completed_successfully

  models:
    build:
      context: packages/models
    volumes:
      - .:/app/packages/models
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    driver: local
